apiVersion: batch/v1
kind: CronJob
metadata:
  name: senaite-db-backup
spec:
  schedule: "0 0 * * *"   # every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup
            image: postgres:15
            env:
            - name: PGPASSWORD
              value: senaitepass
            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /mnt/data/backups
              DATE=$(date +%Y-%m-%d_%H-%M-%S)
              pg_dump \
                -h senaite-postgres-service \
                -U senaiteuser \
                senaite \
                > /mnt/data/backups/senaite_$DATE.sql
            volumeMounts:
            - name: senaite-data
              mountPath: /mnt/data
          volumes:
          - name: senaite-data
            persistentVolumeClaim:
              claimName: senaite-data-pvc
