apiVersion: v1
kind: PersistentVolume
metadata:
  name: senaite-smb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
    - uid=0
    - gid=0
    - noperm
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: senaite-smb-volume
    volumeAttributes:
      source: "//192.168.11.4/senaite"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
